config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: pxhgpeza
      host: john.db.elephantsql.com
      pass: vMHuscohVvjB2TfVxID5Bh6EDxAsur6w
      port: 5432
      schema: pxhgpeza
      threads: 8
      type: postgres
      user: pxhgpeza
  target: prod
